name: ROS test runner
on: [push]
jobs:
  run_ros_tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build the docker-compose stack
      - run:  mkdir -p ros_ws/src
      - run:  mv apr_sim ros_ws/src
      - run:  mv Dockerfile ros_ws
      - run:  mv run_and_check_test.sh ros_ws
      - run:  cd ros_ws && docker build .
